---
project_name: hook-test

release:
  github:
    owner: golangci
    name: golangci-lint

nfpms:
    id: hook-test-nfpm-id
    package_name: hook-test
    file_name_template: "'{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Tux
    vendor: Simon Sawert
    homepage: https://sawert.se
    description: Some cool hooks
    license: GPL3

    formats:
      - deb
      - rpm
