---
project_name: hook-test

release:
  github:
    owner: bombsimon
    name: hook-test

builds:
  - binary: hook-test
    goos:
      - darwin
      - windows
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - 386
      - ppc64le
      - s390x
      - mips64
      - mips64le
    goarm:
      - 6
      - 7
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm64
    main: ./cmd/hook/
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

nfpms:
  -
    id: hook-test-nfpm-id
    package_name: hook-test
    file_name_template: "'{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Tux
    vendor: Simon Sawert
    homepage: https://sawert.se
    description: Some cool hooks
    license: GPL3

    formats:
      - deb
      - rpm
