language: go
go:
  - "1.10"

install:
  - go get -v github.com/golang/dep/cmd/dep
  - dep ensure -v -vendor-only

env:
  global:
    - CC_TEST_REPORTER_ID=6628fd37dd1f7c9205f51089e5a3f13bee964598aa834ca5d521bae660dc5002

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: 
  - go test -v -coverprofile c.out ./...

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email:
    on_success: change
    on_failure: change

# vim: set ts=2 sw=2 et:
